# vim: ts=2:sw=2
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Terminal
#

export TERMINAL='kitty'

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
if command -v most &>/dev/null
then
    export PAGER='most'
else
    export PAGER='less'
fi

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# fpath config
fpath=(
  $HOME/bin/wd
  $fpath
)
# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# GO
export GOPATH=$HOME/go

# Android Home
export ANDROID_PATH=$HOME/Android/Sdk

# Pyenv Home
export PYENV_ROOT=$HOME/.pyenv

# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/.local/bin
  $HOME/.gem/ruby/2.6.0/bin
  /usr/local/{bin,sbin}
  /usr/local/go/bin
  $GOPATH/bin
  $ANDROID_PATH/tools
  $ANDROID_PATH/tools/bin
  $ANDROID_PATH/platform-tools
  $PYENV_ROOT/bin
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi
