#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Language settings
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Colorterm
export COLORTERM=truecolor

# Stop ZSH vim mode delay
export KEYTIMEOUT=1

# Enable BUILDKIT for docker
export DOCKER_BUILDKIT=0

# Enable GO module
export GO111MODULE=on

# GO private repo
export GOPRIVATE=github.com/en-trak
