#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Language settings
export LC_ALL=en_HK.UTF-8
export LANG=en_HK.UTF-8

# Colorterm
export COLORTERM=truecolor

# Stop ZSH vim mode delay
export KEYTIMEOUT=1

# Enable BUILDKIT for docker
export DOCKER_BUILDKIT=0

# Better yaourt colors
export YAOURT_COLORS="nb=1:pkg=1:ver=1;32:lver=1;45:installed=1;42:grp=1;34:od=1;41;5:votes=1;44:dsc=0:other=1;35"

# Enable GO module
export GO111MODULE=on

# GO private repo
export GOPRIVATE=github.com/en-trak

# FZF default command
export FZF_DEFAULT_COMMAND='find . -path "*/\.git" -prune -o -type f -print -o -type l -print | sed s/^..//'
