# vim: ts=2:sw=2
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# zsh-autosuggestions async config; any value can be set
source $HOME/.zprezto/modules/prompt/external/agkozak-zsh-prompt/agkozak-zsh-prompt.plugin.zsh

ZSH_AUTOSUGGEST_UES_ASYNC="zap"

alias zshrc="$EDITOR ~/.zshrc"
alias open="xdg-open"

# if command -v podman &> /dev/null
# then
#   alias docker="podman"
# fi

# this will use the xclip to achive maclike copy and paste pipe action
# this will not work if the xclip is not installed
if command -v xclip &> /dev/null
then
    alias cbcopy='xclip -in -selection clipboard'
    alias cbpaste='xclip -out -selection clipboard'
else
    alias cbcopy='echo notImplemented'
    alias cbpaste='echo notImplemented'
fi

# use for less to have syntax highlight
# need to install source-highlight package
if command -v source-highlight-esc.sh &> /dev/null
then
  export LESSOPEN='| source-highlight-esc.sh %s'
  export LESS=' -R '
fi

# Agkozak themes config
AGKOZAK_BLANK_LINES=1
AGKOZAK_LEFT_PROMPT_ONLY=1
AGKOZAK_CUSTOM_SYMBOLS=( '⇣⇡' '⇣' '⇡' '+' 'x' '!' '>' '?' )

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/bin/terraform terraform

export NVM_DIR="${HOME}/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

wd() {
  . /home/linnovs/bin/wd/wd.sh
}

tmux_rename() {
  if [[ -z "$1" ]]
  then
    tmux rename-window $(basename $PWD)
  else
    tmux rename-window $1
  fi
}

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
