# vim: ts=2:sw=2
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# zsh-autosuggestions async config; any value can be set
source $HOME/.zprezto/modules/prompt/external/agkozak-zsh-prompt/agkozak-zsh-prompt.plugin.zsh

ZSH_AUTOSUGGEST_UES_ASYNC="zap"

alias zshrc="$EDITOR ~/.zshrc"
alias open="xdg-open"
alias gotop="TERM=xterm gotop"

# if command -v podman &> /dev/null
# then
#   alias docker="podman"
# fi

# this will use the xclip to achive maclike copy and paste pipe action
# this will not work if the xclip is not installed
if command -v xclip &> /dev/null
then
  alias cbcopy='xclip -in -selection clipboard'
  alias cbpaste='xclip -out -selection clipboard'
else
  alias cbcopy='echo notImplemented'
  alias cbpaste='echo notImplemented'
fi

# this will set vim to be alias of nvim (if nvim is found)
if command -v nvim &> /dev/null
then
  alias vim='nvim'
fi

# use for less to have syntax highlight
# need to install source-highlight package
if command -v source-highlight-esc.sh &> /dev/null
then
  export LESSOPEN='| source-highlight-esc.sh %s'
  export LESS=' -R '
fi

# Agkozak themes config
AGKOZAK_BLANK_LINES=1
AGKOZAK_LEFT_PROMPT_ONLY=1
AGKOZAK_CUSTOM_SYMBOLS=( '⇣⇡' '⇣' '⇡' '+' 'x' '!' '>' '?' )

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/bin/terraform terraform

if command -v kubectl &> /dev/null
then
  source <(kubectl completion zsh)
fi

export NVM_DIR="${HOME}/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

alias ssh="TERM=xterm-256color ssh"

wd() {
  . /home/linnovs/bin/wd/wd.sh
}

tmux_rename() {
  if [[ -z "$1" ]]
  then
    tmux rename-window $(basename $PWD)
  else
    tmux rename-window $1
  fi
}

code() {
  if [[ ! -z "$TMUX" ]];then
    tmux split-window -l 20% -v -d
    vim
  fi
}


uuidgenbytes() {
  uuid=$(uuidgen | tr -d - )
  bytes=""
  for i in {1..32..2}
  do
    bytes+=$(printf '\\\\x%s' "$(echo $uuid | cut -c ${i}-$((i+1)))")
  done
  echo $bytes
}

uuidtobytes() {
  uuid=$(echo $1 | tr -d -)
  bytes=""
  for i in {1..32..2}
  do
    bytes+=$(printf '\\\\x%s' "$(echo $uuid | cut -c ${i}-$((i+1)))")
  done
  echo $bytes
}

uuidtobase64() {
  uuid=$(echo $1 | tr -d -)
  echo -n "$(uuidtobytes $uuid)"| base64
}

goplay() {
  tempdir=$(mktemp -d -t goplay.XXXXX)
  pushd $PWD
  cd $tempdir
  go mod init github.com/linnovs/playground
  cat <<EOF > main.go
package main

import "fmt"

func main() {
	fmt.Println("helloworld")
}
EOF
  vim main.go
  popd
  rm -rf $tempdir
}

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/linnovs/google-cloud-sdk/path.zsh.inc' ]; then . '/home/linnovs/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/linnovs/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/linnovs/google-cloud-sdk/completion.zsh.inc'; fi
